export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>LastHumanCoder</title>
  <base href="/my_website/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>*,html,body{padding:0;margin:0}
</style><link rel="stylesheet" href="styles-2G66T5LL.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-2G66T5LL.css"></noscript><style ng-app-id="ng">.main[_ngcontent-ng-c972804556]{width:100%;padding:0;margin:0}</style><style ng-app-id="ng">.desktop[_ngcontent-ng-c982444100]{height:100vh;width:100vw;background:linear-gradient(135deg,#2d0b33,#1a1a2e);overflow:hidden;position:relative;padding:1rem;box-sizing:border-box}.selection-box[_ngcontent-ng-c982444100]{position:absolute;border:1px solid #4285f4;background-color:#4285f433;pointer-events:none;z-index:1000}</style><style ng-app-id="ng">.icon-wrap[_ngcontent-ng-c1441310879]{width:6rem;height:6rem;margin:.5rem}.icon[_ngcontent-ng-c1441310879]{width:80px;height:80px;border:2px solid transparent;border-radius:8px;padding:8px;text-align:center;-webkit-user-select:none;user-select:none;cursor:pointer;display:flex;flex-direction:column;align-items:center;justify-content:center;transition:border-color .2s ease,background-color .2s ease}.icon.selected[_ngcontent-ng-c1441310879]{border-color:#9370db;background-color:#9370db33}.icon[_ngcontent-ng-c1441310879]:hover{color:#fff}.icon[_ngcontent-ng-c1441310879]   .icon-image[_ngcontent-ng-c1441310879]{width:48px;height:48px}.icon[_ngcontent-ng-c1441310879]   .icon-label[_ngcontent-ng-c1441310879]{margin-top:4px;font-size:12px;color:#fff;word-wrap:break-word;text-align:center}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["mousedown","mouseup","dblclick"],[]);</script>
  <app-root ng-version="19.2.7" _nghost-ng-c972804556 ngh="2" ng-server-context="ssg"><main _ngcontent-ng-c972804556 class="main"><app-desktop _ngcontent-ng-c972804556 _nghost-ng-c982444100 ngh="1"><div _ngcontent-ng-c982444100 cdkdrop class="desktop" jsaction="mousedown:;mouseup:;"><app-icon _ngcontent-ng-c982444100 _nghost-ng-c1441310879 ngh="0"><div _ngcontent-ng-c1441310879 cdkdrag class="cdk-drag icon-wrap" jsaction="mousedown:;"><div _ngcontent-ng-c1441310879 class="icon" jsaction="mousedown:;dblclick:;"><img _ngcontent-ng-c1441310879 class="icon-image" alt="notes" src="assets/icons/txt.svg"><div _ngcontent-ng-c1441310879 class="icon-label">notes</div></div></div><!----></app-icon><app-icon _ngcontent-ng-c982444100 _nghost-ng-c1441310879 ngh="0"><div _ngcontent-ng-c1441310879 cdkdrag class="cdk-drag icon-wrap" jsaction="mousedown:;"><div _ngcontent-ng-c1441310879 class="icon" jsaction="mousedown:;dblclick:;"><img _ngcontent-ng-c1441310879 class="icon-image" alt="cv" src="assets/icons/pdf.svg"><div _ngcontent-ng-c1441310879 class="icon-label">cv</div></div></div><!----></app-icon><app-icon _ngcontent-ng-c982444100 _nghost-ng-c1441310879 ngh="0"><div _ngcontent-ng-c1441310879 cdkdrag class="cdk-drag icon-wrap" jsaction="mousedown:;"><div _ngcontent-ng-c1441310879 class="icon" jsaction="mousedown:;dblclick:;"><img _ngcontent-ng-c1441310879 class="icon-image" alt="Program.exe" src="assets/icons/exe.svg"><div _ngcontent-ng-c1441310879 class="icon-label">Program.exe</div></div></div><!----></app-icon><app-icon _ngcontent-ng-c982444100 _nghost-ng-c1441310879 ngh="0"><div _ngcontent-ng-c1441310879 cdkdrag class="cdk-drag icon-wrap" jsaction="mousedown:;"><div _ngcontent-ng-c1441310879 class="icon" jsaction="mousedown:;dblclick:;"><img _ngcontent-ng-c1441310879 class="icon-image" alt="Projects" src="assets/icons/dir.svg"><div _ngcontent-ng-c1441310879 class="icon-label">Projects</div></div></div><!----></app-icon><!----><!----><!----></div></app-desktop></main><router-outlet _ngcontent-ng-c972804556></router-outlet><!----></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-CBE5O6BC.js" type="module"></script>

<script id="ng-state" type="application/json">{"2446294346":{"b":[{"id":"1","name":"notes","iconUrl":"assets/icons/txt.svg","type":"text","selected":false},{"id":"2","name":"cv","iconUrl":"assets/icons/pdf.svg","type":"pdf","selected":false},{"id":"3","name":"Program.exe","iconUrl":"assets/icons/exe.svg","type":"exe","selected":false},{"id":"4","name":"Projects","iconUrl":"assets/icons/dir.svg","type":"directory","selected":false}],"h":{},"s":200,"st":"OK","u":"/assets/mock/desktop-files.json","rt":"json"},"__nghData__":[{"c":{"0":[]}},{"t":{"3":"t0","5":"t1","6":"t2"},"c":{"3":[{"i":"t0","r":1,"x":4}],"5":[],"6":[]}},{"c":{"2":[]}}]}</script></body></html>`;